align_args: false
align_parameter: false
align_table_field: false
break_after_functioncall_lp: true
break_after_functiondef_lp: true
break_after_table_lb: true
break_before_functioncall_rp: true
break_before_functiondef_rp: true
break_before_table_rb: true
chop_down_kv_table: true
chop_down_parameter: true
chop_down_table: true
continuation_indent_width: 2
extra_sep_at_table_end: true
indent_width: 2
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
spaces_inside_table_braces: true
