#!/usr/bin/env python

import os


def link(origin, destination):
    os.symlink(origin, destination)


if __name__ == '__main__':
    home = os.path.expanduser('~')
    excludes = ('.DS_Store', '.gitmodules')

    for file in os.listdir('.'):
        if not file.startswith('.'):
            continue

        if file in excludes:
            continue

        if not (os.path.isfile(file) or os.path.islink(file)):
            continue

        destination_file = os.path.join(home, file)

        if os.path.exists(destination_file):
            print '{} already exists'.format(file)
            continue

        link(os.path.abspath(file), destination_file)

        print '{} has been linked in your home folder'.format(file)
