- hosts: localhost
  remote_user: dirn

  vars:
    ansible: ~/.ansible
    dotfiles: "{{ ansible }}/dotfiles"
    rc_file: ~/.extra
    pyenv: /Users/{{ ansible_ssh_user }}/.pyenv
    python_version: 3.4.3
    python_xp_version: 2.7.9
    ruby_version: 2.2.0
    ruby_versions: [2.0.0-p598, 2.1.5, 2.2.0]
    venv: ~/.pyenv/versions/{{ python_version }}/bin/pyvenv

  roles:
    - role: osx
      tags: osx, configuration

    - role: dirn.dotfiles
      dotfiles_github_repo: git@github.com:dirn/dotfiles.git
      dotfiles_dest: "{{ dotfiles }}"
      dotfiles_keep_updated: true
      tags: dotfiles

    - role: dirn.homebrew
      homebrew_libraries:
        - ag # the_silver_searcher
        - ansible
        - aspell
        - ctags
        - go
        - hg # mercurial
        - keybase
        - openssl
        - readline
        - tree
        - wget
      homebrew_casks:
        # 1password only syncs with iCloud when installed from the App Store.
        - alfred
        - appzapper
        # cloud comes from the appstore
        # dash comes from the appstore
        - dropbox
        - flux
        # google-chrome-beta only in homebrew/versions tap
        - hipchat
        - iterm2
        - kaleidoscope
        - parallels-desktop
        - rdio
        - slack
        - skitch
        - transmit
        - virtualbox # if VirtualBox is running, this will fail
        - vmware-fusion
        - xquartz
      homebrew_casks_with_sudo:
        - seil
      tags: homebrew
      # TODO: rc file
    # - name: Configure Homebrew Cask
    #   lineinfile: >
    #     dest={{ rc_file }}
    #     state=present
    #     create=yes
    #     line="export HOMEBREW_CASK_OPTS=\"--appdir=/Applications\""
    #   tags: osx

    - role: ruby
      rc_file: "{{ rc_file }}"
      tags: ruby

    - role: dirn.docker
      docker_install_machine: true
      docker_install_compose: true
      tags: docker

    - role: dirn.vim
      vim_install_gvim: true
      vim_install_nvim: true
      vim_install_neobundle: true
      tags: vim
      # TODO: rc file
      # TODO: NeoVim rc file
      # TODO: link to Vim
      # TODO: default editor

    - role: dirn.git
      git_runcom: "{{ rc_file }}"
      git_utility_root: ~/.local/bin
      git_install_gitsh: true
      git_install_hub: true
      tags: git
      # TODO: rc file
      # ~/.gitconfig
      # ~/.gitignoreglobal

    - role: dirn.psql
      tags: psql
      # TODO: rc file

    - role: dirn.tmux
      tmux_install_tmuxinator: true
      tmux_tmuxinator_executable: ~/.rbenv/versions/{{ ruby_version }}/bin/gem
      tmux_install_tmuxp: true
      tmux_tmuxp_virtualenv: ~/.local/venvs/tmuxp
      tmux_tmuxp_virtualenv_command: "{{ venv }}"
      tags: tmux
      # TODO: rc file
      # TODO: battery.sh
      # TODO: Link tmupx into ~/.local/bin

    - role: zsh
      dotfiles: "{{ dotfiles }}"
      tags: zsh

  tasks:
    # Dotfiles

    - name: Ensure the Ansible directory exists
      file: path={{ ansible }} state=directory

    - name: Ensure the local bin folder exists
      file: path=~/.local/bin state=directory

    # Beautification

    - name: Download colorschemes
      git: repo=git@github.com:{{ item.src }}.git dest={{ ansible }}/colorschemes/{{ item.dest }}
      with_items:
        - src: chriskempson/base16-iterm2
          dest: base16-iterm2
        - src: altercation/solarized
          dest: solarized

    - name: Download fonts
      git: repo=git@github.com:{{ item.src }}.git dest={{ ansible }}/fonts/{{ item.dest }}
      with_items:
        - src: Lokaltog/powerline-fonts
          dest: powerline-fonts

    # Configuration

    - name: Add alias to run this playbook
      lineinfile: >
        dest={{ rc_file }}
        state=present
        create=yes
        line="alias play=\"ansible-playbook --ask-sudo-pass --inventory-file localhost, --connection=local {{ dotfiles }}/playbook.yml\""

    # Zsh

    - name: Install Zsh
      homebrew: name=zsh state=present
      tags: zsh

    - name: Add Homebrew's Zsh to /etc/shells
      sudo: yes
      lineinfile: dest=/etc/shells line="/usr/local/bin/zsh" state=present
      tags: zsh

    - name: Check shell
      shell: echo $SHELL
      register: shell_name
      changed_when: shell_name.stdout != '/usr/local/bin/zsh'
      tags: zsh

    - name: Use Homebrew's Zsh
      shell: chsh -s /usr/local/bin/zsh
      register: zsh_test
      when: shell_name.stdout != '/usr/local/bin/zsh'
      tags: zsh

    - name: Install Prezto
      git: repo=git@github.com:sorin-ionescu/prezto.git dest=~/.zprezto
      tags: zsh

    - name: Link Prezto's dotfiles
      file: src=~/.zprezto/runcoms/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - zlogin
        - zlogout
        - zprofile
        - zshenv
      tags: zsh

    - name: Link Zsh's dotfiles
      file: src={{ dotfiles }}/zsh/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - zpreztorc
        - zshrc
        - aliases
        - exports
        - functions
      tags: zsh

    # Python

    - name: Install Python
      homebrew: name={{ item }} state=present
      with_items:
        - pyenv
        - pyenv-virtualenv
        - pyenv-virtualenvwrapper
      tags: python

    - name: Configure virtualenvwrapper
      lineinfile: >
        dest={{ rc_file }}
        state=present
        create=yes
        line="{{ item }}"
      with_items:
        - export WORKON_HOME=\"$HOME/.virtualenvs\"
        - export PROJECT_HOME=\"$HOME/development\"
      tags: python

    - name: Source pyenv
      lineinfile: >
        dest={{ rc_file }}
        state=present
        create=yes
        line="{{ item }}"
      with_items:
        - if which pyenv > /dev/null; then
        - "    export PYENV_ROOT=\\\"$HOME/.pyenv\\\""
        - "    export PATH=\\\"$PYENV_ROOT/bin:$PATH\\\""
        - "    eval \\\"$(pyenv init -)\\\""
        - "    pyenv virtualenvwrapper_lazy"
        - "fi # pyenv"
      tags: python

    - name: Install Python versions
      command: creates=~/.pyenv/versions/{{ item }} pyenv install {{ item }}
      with_items: python_versions
      tags: python

    - name: Set global Python versions
      lineinfile: >
        dest={{ pyenv }}/version
        state=present
        create=yes
        insert{{ item.insert_at|default('after') }}={{ item.pattern|default('EOF') }}
        line={{ item.version }}
      with_items:
        - version: 2.7.9 # First for stuff that installs with Python
          insert_at: before
          pattern: BOF
        - version: 3.4.3
          insert_at: after
          pattern: 2.7.9
        - version: 2.6.9
        - version: 3.3.6
        - version: pypy-2.5.0
        - version: pypy3-2.4.0
      tags: python

    - name: Exclude old global Python versions
      lineinfile: >
        dest={{ pyenv }}/version
        state=absent
        line={{ item }}
      with_items:
        - 3.4.2
      tags: python

    - name: Set local Python versions
      lineinfile: >
        dest=~/.python-version
        state=present
        create=yes
        insert{{ item.insert_at|default('after') }}={{ item.pattern|default('EOF') }}
        line={{ item.version }}
      with_items:
        - version: 3.4.3
          insert_at: before
          pattern: BOF
        - version: 2.7.9
          insert_at: after
          pattern: 3.4.3
        - version: 2.6.9
        - version: 3.3.6
        - version: pypy-2.5.0
        - version: pypy3-2.4.0
      tags: python

    - name: Exclude old local Python versions
      lineinfile: >
        dest=~/.python-version
        state=absent
        line={{ item }}
      with_items:
        - 3.4.2
      tags: python

    # Install and link devpi first so other pip tasks can use it.
    - name: Install devpi
      pip: >
        name=devpi-server
        executable=/Users/{{ ansible_ssh_user }}/.local/venvs/devpi/bin/pip
        virtualenv=~/.local/venvs/devpi
        virtualenv_command={{ venv }}
        state=present
      tags: python

    - name: Link devpi
      file: src=~/.local/venvs/devpi/bin/devpi-server dest=~/.local/bin/devpi-server state=link
      tags: python

    - name: Start devpi
      command: ~/.local/bin/devpi-server --start
      register: devpi
      changed_when: devpi.stdout.startswith('starting background')
      tags: python

    - name: Configure pip to use devpi
      lineinfile: >
        dest=~/.pip/pip.conf
        state=present
        create=yes
        line="{{ item }}"
      with_items:
        - "[global]"
        - index-url = http://localhost:3141/root/pypi/+simple/
      tags: python

    - name: Install bpython
      pip: >
        name=bpython
        executable=/Users/{{ ansible_ssh_user }}/.local/venvs/bpython/bin/pip
        virtualenv=~/.local/venvs/bpython
        virtualenv_command={{ venv}}
        state=latest
      tags: python

    - name: Install twine
      pip: >
        name=twine
        executable=/Users/{{ ansible_ssh_user }}/.local/venvs/twine/bin/pip
        virtualenv=~/.local/venvs/twine
        virtualenv_command={{ venv }}
        state=latest
      tags: python

    - name: Install wheel
      pip: >
        name=wheel
        executable=/Users/{{ ansible_ssh_user }}/.local/venvs/wheel/bin/pip
        virtualenv=~/.local/venvs/wheel
        virtualenv_command={{ venv }}
        state=latest
      tags: python

    - name: Link global Python executables
      file: src=~/.local/venvs/{{ item.venv }}/bin/{{ item.executable|default(item.venv) }} dest=~/.local/bin/{{ item.executable|default(item.venv) }} state=link
      with_items:
        - venv: bpython
        - venv: twine
      tags: python

    - name: Install pip libraries (2.7)
      pip: name={{ item }} executable={{ pyenv }}/versions/{{ python_xp_version }}/bin/pip state=latest
      with_items:
        - bpython
        - flake8-docstrings # flake8 plus pep257
        - pip
        - setuptools
      tags: python

    - name: Install pip libraries (3.4)
      pip: name={{ item }} executable={{ pyenv }}/versions/{{ python_version }}/bin/pip state=latest
      with_items:
        - bpython
        - flake8-docstrings # flake8 plus pep257
        - pip
        - setuptools
      tags: python

    - name: Configure virtualenvwrapper
      lineinfile: >
        dest=~/.virtualenvs/postmkvirtualenv
        state=present
        create=yes
        mode=0775
        line="{{ item }}"
      with_items:
        - "#!/bin/zsh"
        - pip install bpython
        - pip install flake8-docstrings
        - pip install neovim
        - pip install wheel
      tags: python

    # Ruby

    - name: Install Ruby
      homebrew: name={{ item }} state=present
      with_items:
        - rbenv
        - ruby-build
      tags: ruby

    - name: Source rbenv
      lineinfile: >
        dest={{ rc_file }}
        state=present
        create=yes
        line="if which rbenv > /dev/null; then eval \"$(rbenv init -)\"; fi"
      tags: ruby

    - name: Install Ruby versions
      command: creates=~/.rbenv/versions/{{ item }} rbenv install {{ item }}
      with_items: ruby_versions
      tags: ruby

    - name: Set global Ruby version
      lineinfile: >
        dest=~/.rbenv/version
        state=present
        create=yes
        insertbefore=BOF
        line={{ ruby_version }}
      tags: ruby

    - name: Install gems
      gem: name={{ item }} executable=~/.rbenv/versions/{{ ruby_version }}/bin/gem state=latest
      with_items:
        - lunchy
      tags: ruby

    # Weechat

    - name: Install WeeChat
      homebrew: name=weechat install_options=with-aspell,with-perl,with-python,with-ruby state=present
      tags: weechat

    - name: Install WeeChat gems
      gem: name={{ item }} state=present
      with_items:
        - terminal-notifier
        - weechat
      tags: weechat

    # http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install
    - name: Disable global disutils prefix
      lineinfile: >
        dest=~/.pydistutils.cfg
        state=present
        create=yes
        line={{ item }}
      with_items:
        - "[install]"
        - prefix=
      changed_when: false
      tags: weechat

    - name: Install WeeChat pip libraries
      pip: name=pync executable=/usr/local/bin/pip2 extra_args=--user state=latest
      tags: weechat

    # Leaving this around would use pip to try to install things to /lib.
    - name: Reenable global disutils prefix
      file: path=~/.pydistutils.cfg state=absent
      changed_when: false
      tags: weechat

    - name: Link WeeChat's dotfiles
      file: src={{ dotfiles }}/weechat dest=~/.weechat state=link
      tags: weechat

    # SSH

    - name: Link SSH dotfiles
      file: src={{ dotfiles }}/ssh/config dest=~/.ssh/config state=link
      tags: ssh

    # npm

    - name: Install npm
      homebrew: name=npm
      tags: npm

    # MongoDB

    - name: Install MongoDB
      homebrew: name=mongodb state=present
      tags: mongo

    - name: Install MongoDB Shell Enhancements
      npm: name=mongo-hacker global=yes state=latest
      tags: mongo
