#!/bin/sh

if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -f "$HOMEBREW_BUNDLE_FILE" ]; then
    echo "Updating Homebrew bundle."
    brew bundle
fi

if command -v pyenv >/dev/null 2>&1; then
    echo "Installing Python versions."
    pyenv install --skip-existing 3.9.0
    pyenv global 3.9.0

    echo "Installing Python libraries."
    python -m pip install --upgrade pip
    pip install black bpython flake8 flake8_bugbear mypy pre-commit pudb pynvim virtualfish
fi

if command -v fish >/dev/null 2>&1; then
  if command -v vf >/dev/null 2>&1; then
      echo "Installing virtualfish plugins."
      fish -c "vf install auto_activation global_requirements"
  fi

  if [ -f "$HOME/.virtualenvs/global_requirements.txt" ]; then
      echo "Installing requirements into virtual environments."
      # The only entry point to installing the requirements is through
      # `vf requirements`. This opens the global requirements file into $EDITOR
      # and then runs `pip install` after the editor exits. By using `echo` as the
      # editor instead, we can install the requirements without further user
      # interaction.
      # TODO: This can be switched to `true` in fish 3.2.
      fish -c "set EDITOR echo; vf requirements"
  fi
fi

# Make the Maildir directories. isync seems to want them to exist rather than
# just creating them if they aren't there.
mkdir -p ~/Mail/bigapplepy
mkdir -p ~/Mail/dirnonline
mkdir -p ~/Mail/gmail
mkdir -p ~/Mail/pygotham
