set nocompatible

" --- Pathogen ---
execute pathogen#infect()

" --- Configuration ---
syntax on
filetype plugin indent on

let mapleader=','
let maplocalleader='\\'

set encoding=utf8
set lazyredraw                  " no redraw during macros (much faster)
set linebreak
set nowrap
set report=0                    " :cmd always shows changed line count
set textwidth=80

set mouse=a                     " turn on mouse support

" --- Guides ---
set cursorline                  " highlight current line
set showmatch                   " show matching brackets ...
set matchpairs+=<:>
set matchtime=5                 " ... for 5 seconds
" Conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

" Show a rule
if exists('&colorcolumn')
    highlight ColorColumn guibg=Red
    set colorcolumn=+1
endif

" --- History ---
set history=256

" --- Appearance ---
set background=dark

if has('gui_running') || &t_Co > 8
    set t_Co=256

    colorscheme argonaut
    let g:solarized_termcolors=&t_Co
    let g:solarized_visibility="high"
    let g:solarized_contrast="high"

    if has('gui_running')
        set guifont=Ubuntu\ Mono\ derivative\ Powerline:h16
        set lines=85 columns=280
    endif
endif

set laststatus=2                " always show status line
set noshowmode                  " hide the mode text, Powerline shows it

set display+=lastline
set listchars=tab:▸\ ,eol:¬

set ruler                       " show the cursor position

set scrolloff=2                 " lines above and below the current line
set sidescrolloff=2

set number                      " show line numbers

set title                       " show the filename in the window's title

" --- Behavior ---
set confirm

set backspace=indent,eol,start  " allow backspacing everywhere in edit mode

set complete=.,w,b,u,t          " this should be the default, but just in case
set completeopt=longest,menuone,preview

set spell                       " use spell check

set timeoutlen=500

" --- Search ---
set ignorecase                  " make search case insensitive ...
set smartcase                   " ... unless an uppercase character is used
set incsearch
set hlsearch

" --- Whitespace ---
set autoindent

set expandtab                   " spaces > tabs
set shiftround                  " indents to a multiple of shiftwidth
set shiftwidth=4
set softtabstop=4
set tabstop=8

" --- Mappings ---
" Make word uppercase
nnoremap <c-u> mzgUiw`z
" Make word lowercase (down, because <c-l> is used for navigation)
nnoremap <c-d> mzguiw`z

" Clear search
nnoremap <silent> <leader><space> :nohlsearch<cr>

" Reindent a file
nnoremap <silent> <leader><tab> gg=G

" Select (charwise) the contents of the current line, excluding indentation.
" Great for pasting Python lines into REPLs.
nnoremap vv ^vg_

" Exit insert mode
inoremap jk <esc>

" Navigation
nnoremap H 0
nnoremap L $
vnoremap L g_

" Keystroke savers
nnoremap ; :
vnoremap ; :

" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv

" Quickly change windows
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" FileType switching
nnoremap <leader>Tp :set ft=python<cr>
nnoremap <leader>Th :set ft=html<cr>
nnoremap <leader>Tj :set ft=htmljinja<cr>
nnoremap <leader>Tr :set ft=rst<cr>

" Don't use the cursor keys
for prefix in ['i', 'n', 'v']
    for key in ['<up>', '<right>', '<down>', '<left>']
        execute prefix . 'noremap ' . key . ' <nop>'
    endfor
endfor

" Retrain my brain
inoremap <esc> <nop>

" --- Typos ---
:iabbrev functino function      " this one has plagued me for years
:iabbrev verison version

:iabbrev :shrug: ¯\_(ツ)_/¯
:iabbrev :tableflip: (╯°□°)╯︵ ┻━┻

" --- Autocmds ---
if has('autocmd') && has('eval')
    augroup misc
        autocmd!

        " Resize splits
        autocmd VimResized * :wincmd =

        " Jump to the last known cursor position if it's valid (from the docs)
        autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   execute "normal g`\"" |
            \ endif
    augroup END

    augroup whitespace
        function! TrimWhitespace()
            %s/\s\+$//e
        endfunction

        autocmd FileWritePre * :call TrimWhitespace()
        autocmd FileAppendPre * :call TrimWhitespace()
        autocmd FilterWritePre * :call TrimWhitespace()
        autocmd BufWritePre * :call TrimWhitespace()
    augroup END
endif

" --- Filetypes ---
augroup filetypes
    autocmd!

    autocmd FileType html,htmldjango,htmljinja,ruby,xml,yaml setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

    " --- .vimrc ---
    " Reload .vimrc if changes are made to it
    autocmd BufWritePost .vimrc source $MYVIMRC
augroup END

" --- Plugin configuration ---

" --- ctrlp ---
let g:ctrlp_dont_split = 'NERD_tree_2'
set wildignore+=*.pyc,*/*.egg-info/*
set wildignore+=migrations                      " bye, bye Django migrations
set wildignore+=.git,.hg
set wildignore+=*.orig
set wildignore+=*.jpg,*.jpeg,*.gif,*.png
set wildignore+=*.mp3
set wildignore+=*.sw?                           " Vim swap files

" --- NERD Tree ---
let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.vim$', '\~$', '\.pyc$', '^__pycache__$', '\.swp$', '\.git$', '\.egg\-info', '\.coverage', '\.tox', '.DS_Store']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:NERDTreeShowHidden=1

nnoremap <leader>fs :NERDTreeToggle<cr>

" --- Powerline ---
let g:Powerline_symbols='unicode'
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

" --- Git Gutter ---
highlight clear SignColumn  " same as the row number column
highlight GitGutterAddDefault          guifg=Green  guibg=NONE  ctermfg=DarkGreen   ctermbg=NONE
highlight GitGutterChangeDefault       guifg=Yellow guibg=NONE  ctermfg=DarkYellow  ctermbg=NONE
highlight GitGutterDeleteDefault       guifg=Red    guibg=NONE  ctermfg=DarkRed     ctermbg=NONE

" --- Gist Vim ---
let g:gist_clip_command='pbcopy'
let g:gist_detect_filetype=1
let g:gist_open_browser_after_post=1

" --- Learn Vimscript the Hard Way ---
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap pb :exe "rightbelow vsplit " . bufname('#')<cr>

augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" --- Fugitive ---
nnoremap <leader>gci :Gcommit<cr>
nnoremap <leader>gco :Gcheckout<cr>
nnoremap <leader>gmv :Gmove<cr>
nnoremap <leader>grm :Gremove<cr>
nnoremap <leader>gst :Gstatus<cr>

" --- Syntastic ---
let g:syntastic_check_on_open = 1

" --- Clam ---
nnoremap ! :Clam<space>
vnoremap ! :ClamVisual<space>
let g:clam_autoreturn=1

" --- Gundo ---
let g:gundo_preview_bottom = 1
let g:gundo_tree_statusline = "gundo"
let g:gundo_preview_statusline = "gundo preview"

nnoremap <leader>gu :GundoToggle<cr>
