set nocompatible

" --- Pathogen ---
call pathogen#infect()

" --- Configuration ---
syntax on
filetype plugin indent on

let mapleader=','
let maplocalleader='\\'

set encoding=utf8
set lazyredraw                  " no redraw during macros (much faster)
set linebreak
set nowrap
set report=0                    " :cmd always shows changed line count
set textwidth=80

set mouse=a                     " turn on mouse support

" --- Guides ---
set cursorline                  " highlight current line
set showmatch                   " show matching brackets ...
set matchpairs+=<:>
set matchtime=5                 " ... for 5 seconds

" Show a rule
if exists('&colorcolumn')
    highlight ColorColumn guibg=Red
    set colorcolumn=+1
endif

" --- History ---
set history=256

" --- Appearance ---
set background=dark

if has('gui_running') || &t_Co > 8
    set t_Co=256

    colorscheme solarized
    let g:solarized_termcolors=256
    let g:solarized_visibility="high"
    let g:solarized_contrast="high"

    if has('gui_running')
        set guifont=Ubuntu\ Mono:h16
    endif
endif

set laststatus=2                " always show status line

set display+=lastline
set listchars=tab:▸\ ,eol:¬

set ruler                       " show the cursor position

set scrolloff=2                 " lines above and below the current line
set sidescrolloff=2

set number                      " show line numbers

" --- Behavior ---
set confirm

set backspace=indent,eol,start  " allow backspacing everywhere in edit mode

set spell                       " use spell check

set timeoutlen=500

" --- Search ---
set ignorecase                  " make search case insensitive ...
set smartcase                   " ... unless an uppercase character is used
set incsearch
set hlsearch

" --- Whitespace ---
set autoindent

set expandtab                   " spaces > tabs
set shiftround                  " indents to a multiple of shiftwidth
set shiftwidth=4
set softtabstop=4
set tabstop=8

" --- Mappings ---
" Make word uppercase
nnoremap          <c-u>             mqgUiw`q
" Make word lowercase
nnoremap          <c-l>             mqguiw`q

" Clear search
nnoremap <silent> <leader>cl        :let @/=''<cr>

" Exit insert mode
inoremap          jk                <esc>

" Don't use the cursor keys
for prefix in ['i', 'n', 'v']
    for key in ['<up>', '<right>', '<down>', '<left>']
        execute prefix . 'noremap ' . key . ' <nop>'
    endfor
endfor

" Retrain my brain
inoremap          <esc>             <nop>

" --- Typos ---
:iabbrev functino function      " this one has plagued me for years

" --- Autocmds ---
if has('autocmd') && has('eval')
    augroup misc
        autocmd!

        " Trim trailing whitespace on save
        autocmd BufWritePre <buffer> :%s/\s\+$//e

        " Jump to the last known cursor position if it's valid (from the docs)
        autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   execute "normal g`\"" |
            \ endif
    augroup END
endif

" --- Filetypes ---
augroup filetypes
    autocmd!

    " --- .vimrc ---
    " Reload .vimrc if changes are made to it
    autocmd BufWritePost .vimrc source $MYVIMRC
augroup END

" --- Plugin configuration ---

" --- NERD Tree ---
let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.vim$', '\~$', '\.pyc$', '\.swp$', '\.git$', '\.egg\-info', '\.coverage', '\.tox', '.DS_Store']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:NERDTreeShowHidden=1

nnoremap <leader>fs :NERDTreeToggle<cr>

" --- Powerline ---
let g:Powerline_symbols='unicode'

" --- Git Gutter ---
highlight clear SignColumn  " same as the row number column
highlight GitGutterAddDefault          guifg=Green  guibg=NONE  ctermfg=DarkGreen   ctermbg=NONE
highlight GitGutterChangeDefault       guifg=Yellow guibg=NONE  ctermfg=DarkYellow  ctermbg=NONE
highlight GitGutterDeleteDefault       guifg=Red    guibg=NONE  ctermfg=DarkRed     ctermbg=NONE

" --- Learn Vimscript the Hard Way ---
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap H 0
nnoremap L $
nnoremap pb :exe "rightbelow vsplit " . bufname('#')<cr>

augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END
