# Remap prefix to <C-a>
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Vim all the things
set-option -g status-keys vi
set-window-option -g mode-keys vi

# Make the splits behave like Vim's
unbind-key %
bind-key s split-window -v
bind-key v split-window -h

# Move around panes like Vim
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Turn off escape delay
set-option -sg escape-time 0

# Resource the config
unbind-key r
bind-key r source-file ~/.tmux.conf \; display 'Resourced ~/.tmux.conf'

# Left-most tab should be the left-most key
set-option -g base-index 1

set-window-option -g utf8 on
set-window-option -g automatic-rename on

# Fix the mouse
set-window-option -g mode-mouse on
set-option -g mouse-resize-pane on
set-option -g mouse-select-pane on
set-option -g mouse-select-window on

# Powerline
source-file ~/.vim/bundle/powerline/powerline/bindings/tmux/powerline.conf

# Copy/paste
set-option -g default-command "command -v reattach-to-user-namespace >/dev/null 2>&1 && reattach-to-user-namespace -l $SHELL || $SHELL -l"
bind -t vi-copy v begin-selection
bind -t vi-copy c copy-selection
bind y send-keys c\;\
       run-shell "tmux save-buffer - | reattach-to-user-namespace pbcopy"
